"use client";

import { CalendarPlus, Loader2, Plus, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { MeetingRecord } from "@/src/lib/business/meeting.repository";

const now = () => new Date().toISOString().slice(0, 16);
export function MeetingManager() {
  const [meetings, setMeetings] = useState<MeetingRecord[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ title: "", startsAt: now(), endsAt: new Date(Date.now() + 3600000).toISOString().slice(0, 16), attendees: "", notes: "", decisions: "", followUps: "", addToCalendar: true });
  useEffect(() => { void load(); }, []);
  async function load() { const response = await fetch("/api/business/meetings"); const data = (await response.json().catch(() => null)) as { meetings?: MeetingRecord[] } | null; if (response.ok) setMeetings(data?.meetings || []); }
  async function save() { if (!form.title.trim()) return; setBusy(true); setError(null); try { const response = await fetch("/api/business/meetings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), attendees: split(form.attendees), followUps: split(form.followUps) }) }); const data = (await response.json().catch(() => null)) as { error?: string } | null; if (!response.ok) throw new Error(data?.error || "회의를 저장하지 못했습니다."); setOpen(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "회의를 저장하지 못했습니다."); } finally { setBusy(false); } }
  return <section className="rounded-app border border-app-border bg-white p-5 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-sm font-semibold text-app-text"><Users size={17} className="text-app-primary" />회의 기록</h2><p className="mt-2 text-xs text-app-muted">참석자, 결정 사항과 후속 작업을 기록합니다.</p></div><button type="button" onClick={() => setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-2xl bg-app-primary px-4 text-xs font-semibold text-white"><Plus size={15} />회의 추가</button></div><div className="mt-4 space-y-2">{meetings.map((meeting) => <article key={meeting.id} className="rounded-2xl border border-app-border bg-app-bg p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-sm font-semibold text-app-text">{meeting.title}</p><p className="mt-1 text-xs text-app-muted">{new Date(meeting.startsAt).toLocaleString("ko-KR")} · {meeting.attendees.join(", ") || "참석자 없음"}</p></div>{meeting.calendarEventId ? <span className="inline-flex items-center gap-1 rounded-full bg-violet-100 px-2 py-1 text-[10px] font-semibold text-violet-700"><CalendarPlus size={11} />캘린더</span> : null}</div>{meeting.decisions ? <p className="mt-3 text-xs leading-5 text-app-text">결정: {meeting.decisions}</p> : null}</article>)}</div>{!meetings.length ? <p className="mt-4 rounded-2xl border border-dashed border-app-border py-8 text-center text-xs text-app-muted">등록된 회의가 없습니다.</p> : null}
  {open ? <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 px-4"><section className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-app border border-app-border bg-white p-6 shadow-app"><div className="flex justify-between"><h3 className="text-lg font-semibold text-app-text">회의 추가</h3><button type="button" onClick={() => setOpen(false)} className="rounded-xl border border-app-border p-2"><X size={15} /></button></div><div className="mt-5 grid gap-3">{([ ["title", "회의 제목", "text"], ["startsAt", "시작", "datetime-local"], ["endsAt", "종료", "datetime-local"], ["attendees", "참석자 (쉼표 구분)", "text"] ] as const).map(([key, label, type]) => <label key={key} className="text-xs font-semibold text-app-muted">{label}<input type={type} value={String(form[key])} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="mt-1 h-10 w-full rounded-xl border border-app-border bg-app-bg px-3 text-sm outline-none focus:border-app-primary" /></label>)}{([ ["notes", "회의 내용"], ["decisions", "결정 사항"], ["followUps", "후속 작업 (쉼표 구분)"] ] as const).map(([key, label]) => <label key={key} className="text-xs font-semibold text-app-muted">{label}<textarea value={String(form[key])} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="mt-1 min-h-20 w-full rounded-xl border border-app-border bg-app-bg p-3 text-sm outline-none focus:border-app-primary" /></label>)}<label className="flex items-center gap-2 rounded-2xl border border-app-border p-3 text-sm font-semibold text-app-text"><input type="checkbox" checked={form.addToCalendar} onChange={(event) => setForm((current) => ({ ...current, addToCalendar: event.target.checked }))} />캘린더에도 일정 추가</label></div>{error ? <p className="mt-3 text-xs text-red-600">{error}</p> : null}<button type="button" disabled={busy || !form.title.trim()} onClick={() => void save()} className="mt-4 inline-flex h-11 w-full items-center justify-center gap-2 rounded-app bg-app-primary text-sm font-semibold text-white disabled:opacity-40">{busy ? <Loader2 size={16} className="animate-spin" /> : <CalendarPlus size={16} />}회의 기록 저장</button></section></div> : null}</section>;
}
function split(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
