"use client";

import { KeyRound, Search } from "lucide-react";
import { useState } from "react";

type Grant = { id: string; source: string; startsAt: string; endsAt: string; status: string };

export function AdminAccessGrants() {
  const [userId, setUserId] = useState("");
  const [days, setDays] = useState(30);
  const [grants, setGrants] = useState<Grant[]>([]);
  const [error, setError] = useState<string | null>(null);
  async function load() { if (!userId.trim()) return; const response = await fetch(`/api/admin/users/${encodeURIComponent(userId.trim())}/access-grants`, { cache: "no-store" }); const body = await response.json().catch(() => ({})) as { grants?: Grant[]; error?: string }; if (!response.ok) throw new Error(body.error || "이용권을 불러오지 못했습니다."); setGrants(body.grants || []); }
  async function grant() { setError(null); try { const response = await fetch(`/api/admin/users/${encodeURIComponent(userId.trim())}/access-grants`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ days }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error || "이용권을 지급하지 못했습니다."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "이용권을 지급하지 못했습니다."); } }
  async function revoke(grantId: string) { const confirmationPhrase = window.prompt("이용권을 회수하려면 REVOKE를 입력하세요."); if (confirmationPhrase !== "REVOKE") return; const response = await fetch(`/api/admin/users/${encodeURIComponent(userId.trim())}/access-grants`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ grantId, confirmationPhrase }) }); if (!response.ok) { const body = await response.json().catch(() => ({})) as { error?: string }; setError(body.error || "회수하지 못했습니다."); return; } await load(); }
  return <section className="rounded-[22px] border border-app-border bg-app-card p-5 shadow-soft"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-app-hover text-app-primary"><KeyRound size={19} /></span><div><h2 className="text-lg font-bold">구독·이용권 관리</h2><p className="mt-1 text-xs text-app-muted">사용자 ID를 기준으로 기간형 접근권한을 지급하거나 회수합니다.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-2xl border border-app-border px-3"><Search size={15} /><input value={userId} onChange={(event) => setUserId(event.target.value)} placeholder="사용자 ID" className="min-w-0 flex-1 bg-transparent text-xs outline-none" /></label><input type="number" min={1} max={3650} value={days} onChange={(event) => setDays(Number(event.target.value))} className="min-h-11 rounded-2xl border border-app-border px-3 text-xs sm:w-32" /><button type="button" onClick={() => void load().catch((caught) => setError(caught.message))} className="min-h-11 rounded-2xl border border-app-border px-4 text-xs font-bold">조회</button><button type="button" onClick={() => void grant()} className="min-h-11 rounded-2xl bg-app-primary px-4 text-xs font-bold text-white">지급</button></div>{error ? <p className="mt-4 rounded-2xl bg-red-50 p-3 text-xs text-red-700">{error}</p> : null}<div className="mt-5 space-y-2">{grants.map((grant) => <article key={grant.id} className="flex flex-col gap-3 rounded-2xl border border-app-border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs font-bold">{grant.source} · {grant.status}</p><p className="mt-1 text-[10px] text-app-muted">{new Date(grant.startsAt).toLocaleString("ko-KR")} ~ {new Date(grant.endsAt).toLocaleString("ko-KR")}</p></div>{grant.status === "active" ? <button type="button" onClick={() => void revoke(grant.id)} className="min-h-11 rounded-2xl border border-red-200 px-4 text-xs font-bold text-red-600">회수</button> : null}</article>)}</div></section>;
}

