"use client";

import { RotateCcw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Job = { id: string; ownerId: string; jobType: string; executionId: string | null; attempt: number; maxAttempts: number; deadLetterReason: string; safePayload: unknown; updatedAt: string };
export function AdminDlqView() {
  const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/automation/admin/dlq", { cache: "no-store" }); const data = await response.json().catch(() => ({})) as { jobs?: Job[]; error?: string }; if (!response.ok) throw new Error(data.error || "DLQ를 불러오지 못했습니다."); setJobs(data.jobs || []); }, []);
  useEffect(() => { void load().catch((caught) => setError(caught.message)); }, [load]);
  async function requeue(jobId: string) { setBusy(jobId); try { const response = await fetch("/api/automation/admin/dlq", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jobId }) }); const data = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(data.error || "재실행에 실패했습니다."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "재실행에 실패했습니다."); } finally { setBusy(null); } }
  return <section className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-bold">관리자 Dead Letter Queue</h2><p className="mt-1 text-xs text-slate-500">Payload는 다시 마스킹되어 표시됩니다. 실패 이유와 시도 횟수를 확인한 뒤 새 Job으로 재실행할 수 있습니다.</p>{error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p> : null}<div className="mt-5 space-y-3">{jobs.map((job) => <article key={job.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><h3 className="text-xs font-bold">{job.jobType} · {job.id}</h3><p className="mt-1 text-[10px] text-slate-500">시도 {job.attempt}/{job.maxAttempts} · {new Date(job.updatedAt).toLocaleString("ko-KR")}</p><p className="mt-2 rounded-lg bg-red-50 p-2 text-[10px] text-red-700">{job.deadLetterReason}</p><pre className="mt-2 max-h-32 overflow-auto rounded-lg bg-slate-950 p-2 text-[9px] text-slate-200">{JSON.stringify(job.safePayload, null, 2)}</pre></div><button type="button" disabled={busy === job.id} onClick={() => void requeue(job.id)} className="inline-flex items-center gap-1 rounded-xl bg-violet-600 px-3 py-2 text-[10px] font-bold text-white disabled:opacity-50"><RotateCcw size={12} />재실행</button></div></article>)}{jobs.length === 0 && !error ? <p className="py-12 text-center text-xs text-slate-400">Dead Letter Job이 없습니다.</p> : null}</div></section>;
}
