"use client";

import { RefreshCw, ShieldCheck, Unplug } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { AUTOMATION_APPS } from "@/src/lib/automation/app-registry";

type Connection = { id: string; appId: string; provider: string; accountLabel: string | null; accountEmail: string | null; grantedScopes: string[]; status: string; credentialStatus: string; expiresAt: string | null; validatedAt: string | null };
const oauthApps = AUTOMATION_APPS.filter((app) => app.oauthTarget).map((app) => app.id);
export function DurableConnectionPanel() {
  const [connections, setConnections] = useState<Connection[]>([]); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/integrations/connections", { cache: "no-store" }); const data = await response.json().catch(() => ({})) as { connections?: Connection[]; error?: string }; if (!response.ok) throw new Error(data.error || "연결 계정을 불러오지 못했습니다."); setConnections(data.connections || []); }, []);
  useEffect(() => { void load().catch((caught) => setError(caught.message)); }, [load]);
  async function start(appId: string) { setBusy(`start:${appId}`); try { const response = await fetch(`/api/integrations/${appId}/oauth/start`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ returnTo: "/?view=automation" }) }); const data = await response.json() as { authorizationUrl?: string; error?: string }; if (!response.ok || !data.authorizationUrl) throw new Error(data.error || "OAuth 연결을 시작하지 못했습니다."); window.location.assign(data.authorizationUrl); } catch (caught) { setError(caught instanceof Error ? caught.message : "OAuth 연결에 실패했습니다."); setBusy(null); } }
  async function action(connection: Connection, name: "test" | "refresh" | "disconnect") { setBusy(`${name}:${connection.id}`); setError(null); try { if (name === "disconnect") { const previewResponse = await fetch(`/api/integrations/connections/${connection.id}/disconnect`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const preview = await previewResponse.json() as { affectedWorkflows?: unknown[]; error?: string }; if (!previewResponse.ok) throw new Error(preview.error || "연결 해제 영향을 확인하지 못했습니다."); if (!window.confirm(`이 연결을 사용하는 워크플로 ${preview.affectedWorkflows?.length || 0}개가 중단될 수 있습니다. 연결을 해제할까요?`)) return; await request(`/api/integrations/connections/${connection.id}/disconnect`, { confirmed: true, reason: "user_confirmed_in_connection_manager" }); } else await request(`/api/integrations/connections/${connection.id}/${name}`, {}); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "연결 작업에 실패했습니다."); } finally { setBusy(null); } }
  return <section className="mb-5 rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-bold">OAuth 연결 계정</h2><p className="mt-1 text-xs text-slate-500">앱별 다중 계정, Scope, Credential 및 만료 상태를 관리합니다. 오류가 발생해도 자동으로 연결 해제하지 않습니다.</p></div><div className="flex flex-wrap gap-1">{oauthApps.map((appId) => <button key={appId} type="button" disabled={busy === `start:${appId}`} onClick={() => void start(appId)} className="rounded-lg border border-violet-200 px-2 py-1 text-[9px] font-bold text-violet-700">+ {appId}</button>)}</div></div>{error ? <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p> : null}<div className="mt-4 grid gap-3 md:grid-cols-2">{connections.map((connection) => <article key={connection.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><ShieldCheck size={18} className={connection.status === "connected" ? "text-emerald-600" : "text-amber-600"} /><div className="min-w-0 flex-1"><h3 className="truncate text-xs font-bold">{connection.appId} · {connection.accountLabel || connection.accountEmail || connection.provider}</h3><p className="mt-1 text-[10px] text-slate-500">{connection.status} · Credential {connection.credentialStatus}</p><p className="mt-1 line-clamp-2 text-[9px] text-slate-400">Scope: {connection.grantedScopes.join(", ") || "Provider-managed"}</p></div></div><div className="mt-3 flex gap-2"><SmallButton label="테스트" onClick={() => void action(connection, "test")} /><SmallButton label="갱신" icon={<RefreshCw size={11} />} onClick={() => void action(connection, "refresh")} /><SmallButton label="연결 해제" icon={<Unplug size={11} />} danger onClick={() => void action(connection, "disconnect")} /></div></article>)}</div></section>;
}
async function request(url: string, body: unknown) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(data.error || "요청에 실패했습니다."); return data; }
function SmallButton({ label, icon, danger, onClick }: { label: string; icon?: React.ReactNode; danger?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-[9px] font-bold ${danger ? "border-red-200 text-red-700" : "border-slate-200 text-slate-600"}`}>{icon}{label}</button>; }
