"use client";

import { ChevronDown, ChevronUp, Loader2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { AppLogo } from "@/components/shared/AppLogo";

type Execution = { id: string; workflowId: string; workflowVersion: number; status: string; executionMode: string; triggerType: string; createdAt: string; completedAt: string | null };
type Step = { id: string; appId: string; actionId: string; actionVersion: number; status: string; riskLevel: string; attempt: number; retryCount: number; input: unknown; output: unknown; preview: unknown; durationMs: number | null; apiRequestId: string | null; rateLimitRemaining: number | null; adapterLatencyMs: number | null; errorMessage: string | null };

export function DurableRunHistory() {
  const [executions, setExecutions] = useState<Execution[]>([]);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [steps, setSteps] = useState<Record<string, Step[]>>({});
  const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/automation/executions", { cache: "no-store" }); const data = await response.json() as { executions?: Execution[] }; if (response.ok) setExecutions(data.executions || []); }, []);
  useEffect(() => { void load(); }, [load]);
  async function toggle(id: string) { if (expanded === id) return setExpanded(null); setExpanded(id); if (steps[id]) return; setLoading(true); try { const response = await fetch(`/api/automation/executions/${id}`, { cache: "no-store" }); const data = await response.json() as { steps?: Step[] }; if (response.ok) setSteps((current) => ({ ...current, [id]: data.steps || [] })); } finally { setLoading(false); } }
  return <section className="overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-base font-bold text-slate-950">영속 실행 내역</h2><p className="mt-1 text-xs text-slate-500">각 Step의 입력, 출력, Preview, 재시도 및 Provider 관측 정보를 확인합니다.</p></div><div className="divide-y divide-slate-100">{executions.map((execution) => <article key={execution.id} className="p-4"><button type="button" onClick={() => void toggle(execution.id)} className="flex w-full items-center gap-3 text-left"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{execution.status}</span><span className="min-w-0 flex-1 truncate text-xs font-bold">{execution.workflowId} v{execution.workflowVersion}</span><span className="text-[10px] text-slate-400">{new Date(execution.createdAt).toLocaleString("ko-KR")}</span>{expanded === execution.id ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button>{expanded === execution.id ? <div className="mt-3 space-y-3">{loading && !steps[execution.id] ? <Loader2 className="animate-spin" size={16} /> : (steps[execution.id] || []).map((step) => <div key={step.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold"><AppLogo appId={step.appId} size={24} /><span>{step.actionId}@{step.actionVersion}</span><span>{step.status}</span><span>{step.riskLevel}</span><span>재시도 {step.retryCount}회</span></div><div className="mt-3 grid gap-2 md:grid-cols-3"><JsonBlock label="입력" value={step.input} /><JsonBlock label="출력" value={step.output} /><JsonBlock label="Preview" value={step.preview} /></div><dl className="mt-3 grid gap-2 text-[10px] text-slate-600 sm:grid-cols-4"><Metric label="API 요청 ID" value={step.apiRequestId || "-"} /><Metric label="Rate Limit" value={step.rateLimitRemaining ?? "-"} /><Metric label="Adapter 지연" value={step.adapterLatencyMs === null ? "-" : `${step.adapterLatencyMs}ms`} /><Metric label="전체 시간" value={step.durationMs === null ? "-" : `${step.durationMs}ms`} /></dl>{step.errorMessage ? <p className="mt-2 rounded-lg bg-red-50 p-2 text-[10px] text-red-700">{step.errorMessage}</p> : null}</div>)}</div> : null}</article>)}{executions.length === 0 ? <p className="py-14 text-center text-xs text-slate-400">실행 기록이 없습니다.</p> : null}</div></section>;
}
function JsonBlock({ label, value }: { label: string; value: unknown }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold text-slate-500">{label}</p><pre className="mt-2 max-h-36 overflow-auto whitespace-pre-wrap break-all text-[9px] text-slate-700">{JSON.stringify(value, null, 2)}</pre></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg bg-slate-50 p-2"><dt className="font-bold text-slate-400">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>; }
